#!/bin/bash
set -e

# Update everything
xbps-install -Suvy

# Disable file system checking.
# The reason is because it fails when checking
# drives that are currently mounted.
# When using Darch, we mount a drive in initramfs
# to mount the squash image.
# We also put it in fstab, so it complains on boot.
touch /fastboot

# Install Darch. It isn't in the main repositories yet,
# so we have to compile it ourselves.
sudo xbps-install -y --repository=$(pwd)/tmprepo darch
ln -s /etc/sv/containerd /etc/runit/runsvdir/default/containerd
# I store containerd on /var/lib/darch/containerd, because /var/lib/darch
# is an external partition. This way, images are persisted across boots.
mkdir -p /etc/containerd
echo "root = \"/var/lib/darch/containerd\"" > /etc/containerd/config.toml

#xbps-install -y NetworkManager
#ln -s /etc/sv/NetworkManager /etc/runit/runsvdir/default/
ln -s /etc/sv/dhcpcd /etc/runit/runsvdir/default/dhcpcd
