#!/bin/bash
set -e

# Update everything
xbps-install -Suvy

# Disable file system checking.
# The reason is because it fails when checking
# drives that are currently mounted.
# When using Darch, we mount a drive in initramfs
# to mount the squash image.
# We also put it in fstab, so it complains on boot.
touch /fastboot

# These commands were used to sign the packages on my personal repo.
#xbps-rindex --sign --signedby 'Paul Knopf <pauldotknopf@gmail.com>' --privkey privkey.pem tmprepo/
#xbps-rindex --sign-pkg --signedby 'Paul Knopf <pauldotknopf@gmail.com>' --privkey privkey.pem tmprepo/darch-0.18.3_1.x86_64.xbps

# Install the key used for my private repository.
mkdir -p /var/db/xbps/keys/
cp private-repo-key.plist /var/db/xbps/keys/fa:bb:ce:c0:d6:72:21:9d:04:8d:b6:83:ea:4c:60:c5.plist
xbps-install -y -S -R https://github.com/pauldotknopf/binary-repos/releases/download/void-linux-release/

# Install Darch.
xbps-install --repository=https://github.com/pauldotknopf/binary-repos/releases/download/void-linux-release/ -y darch

# I store containerd on /var/lib/darch/containerd, because /var/lib/darch
# is an external partition. This way, images are persisted across boots.
mkdir -p /etc/containerd
echo "root = \"/var/lib/darch/containerd\"" > /etc/containerd/config.toml

xbps-install -y NetworkManager
ln -s /etc/sv/NetworkManager /etc/runit/runsvdir/default/
#ln -s /etc/sv/dhcpcd /etc/runit/runsvdir/default/dhcpcd
